run :
  mode : train
  nsamples : 100
  return_prob : False 
  return_traj : False
  sampling_method : ode

device : cuda:0
dataset :
  name : LJ_50
  potential : LJ
  training_data : /home/sherryli/xsli/GenerativeModel/data/lj/liquid_3d/nonperiodic/lj_50_3d_3.0box_T1.00/pos_train.npy
  testing_data : /home/sherryli/xsli/GenerativeModel/data/lj/liquid_3d/nonperiodic/lj_50_3d_3.0box_T1.00/pos_test.npy
  dim : 3
  nparticles: 50
  shape : [50,3]
  boxlength : 5.42
  cutoff : 5.0
  kT : 1.0
  periodic : False
  translation_inv : True
  sigma : 1.0
  epsilon : 1.0
  shift : True

model:
 type : diffusion
 representation : 
   type : vectorfield
   hidden_dim : 500
   force_prefactor : 0.0

 sde :
   type : [GeneralSDE, VP_SDE]
   knots : [0.2]
   schedule : linear
   friction : 10.0

train_parameters :
  max_epochs : 100
  batch_size : 64
  output_freq : 100
  scheduler: exponential
  lr_scheduler_gamma : 0.99

optimizer:
  lr : 3e-4
  beta1 : 0.9
  eps : 1e-8
  warmup : 0 
  grad_clip : 1.

output:
  training_dir: /home/sherryli/xsli/GenerativeModel/training_output/lj/
  testing_dir: /home/sherryli/xsli/GenerativeModel/testing_output/lj/
  model_dir: /home/sherryli/xsli/GenerativeModel/trained_models/lj/
  best_model_dir: /home/sherryli/xsli/GenerativeModel/trained_models/lj/